### ISSUE TITLE
Implement Point Light class

### ISSUE THREAD

**Issue by RickFqt** [RickFqt/cg#39]
After issue #38 , we can create a Point Light class.
**Point light:** It is an infinitesimally small sphere of light with a 3D location in space that emits light rays in all directions. When a light ray strikes a surface, it does so in a specific direction determined by a vector from the strike location on the surface to the point light location in the world space.

Here is how we can create a point light from the xml file:
```xml
<light_source type="point" I="0.3 0.3 0.1" scale="1 1 1" from="0 1.3 -1.7" />
```

Below we have an image representing a point light.

![image](https://github.com/RickFqt/cg/assets/102550763/02cc0e5c-2049-45f4-b0b0-7b7e6173368e)

**Comment by DanteAugusto** [comment]
Tamo junto
